# /etc/skel/.bashrc

if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Alias
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"

export EDITOR=/usr/bin/vim
export PS1='\[\e[0;35m\][\[\e[1;34m\]\u\[\e[0;35m\]@\[\e[0m\]\h \[\e[1;34m\]\w\[\e[0;35m\]]\[\e[0m\]$ '
