# status bar
slstatus &
#dwmstatus 2>&1 >/dev/null &

# wallpaper.
feh --bg-fill ~/Pictures/Mountain.jpg &

# lockscreen
xautolock -time 10 -locker slock &

# Hides the mouse cursor after 3 seconds of inactivity
unclutter -idle 3 &
xrdb ~/.Xresources &
# Saving a dwm log
exec dwm > ~/.dwm.log
